// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmWxPSf3dm2-wvrZ2eqNnj0KYCa161Xfk',
    appId: '1:48915892934:web:0ebfb6c9083294dba965c7',
    messagingSenderId: '48915892934',
    projectId: 'mycityconnect-m-6',
    authDomain: 'mycityconnect-m-6.firebaseapp.com',
    storageBucket: 'mycityconnect-m-6.firebasestorage.app',
    measurementId: 'G-G7SP9TPMGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVn-n6WDRkyAN0CsHpEW5qBjMZ6wQeKSE',
    appId: '1:48915892934:android:910d4d1299a9a5a0a965c7',
    messagingSenderId: '48915892934',
    projectId: 'mycityconnect-m-6',
    storageBucket: 'mycityconnect-m-6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUcOD9zv4eGJQRsTUrdDuh8gq2YSkYXj0',
    appId: '1:48915892934:ios:34332243c79d0bbda965c7',
    messagingSenderId: '48915892934',
    projectId: 'mycityconnect-m-6',
    storageBucket: 'mycityconnect-m-6.firebasestorage.app',
    iosBundleId: 'com.example.m6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUcOD9zv4eGJQRsTUrdDuh8gq2YSkYXj0',
    appId: '1:48915892934:ios:34332243c79d0bbda965c7',
    messagingSenderId: '48915892934',
    projectId: 'mycityconnect-m-6',
    storageBucket: 'mycityconnect-m-6.firebasestorage.app',
    iosBundleId: 'com.example.m6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmWxPSf3dm2-wvrZ2eqNnj0KYCa161Xfk',
    appId: '1:48915892934:web:cab4122c31831cb9a965c7',
    messagingSenderId: '48915892934',
    projectId: 'mycityconnect-m-6',
    authDomain: 'mycityconnect-m-6.firebaseapp.com',
    storageBucket: 'mycityconnect-m-6.firebasestorage.app',
    measurementId: 'G-3RNDNVXSB2',
  );
}
