// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3PXoKDr7gFmFMwlwGg6Cptstoa7XOGM',
    appId: '1:870140854403:web:8293075adf67251f161bb6',
    messagingSenderId: '870140854403',
    projectId: 'flutter-firebase-project-882a5',
    authDomain: 'flutter-firebase-project-882a5.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-882a5.firebasestorage.app',
    measurementId: 'G-HSH83EZFXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6jr1BTB6ZiTq1AOwdqARdHlotaxQnVJ0',
    appId: '1:870140854403:android:c36caaa8c796e7ac161bb6',
    messagingSenderId: '870140854403',
    projectId: 'flutter-firebase-project-882a5',
    storageBucket: 'flutter-firebase-project-882a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUZPbphgPF2deFBxNPJnfH6DwfCL7diZQ',
    appId: '1:870140854403:ios:63d30fd9054c83d2161bb6',
    messagingSenderId: '870140854403',
    projectId: 'flutter-firebase-project-882a5',
    storageBucket: 'flutter-firebase-project-882a5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutterPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUZPbphgPF2deFBxNPJnfH6DwfCL7diZQ',
    appId: '1:870140854403:ios:63d30fd9054c83d2161bb6',
    messagingSenderId: '870140854403',
    projectId: 'flutter-firebase-project-882a5',
    storageBucket: 'flutter-firebase-project-882a5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutterPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD3PXoKDr7gFmFMwlwGg6Cptstoa7XOGM',
    appId: '1:870140854403:web:3545c7b22a612fd4161bb6',
    messagingSenderId: '870140854403',
    projectId: 'flutter-firebase-project-882a5',
    authDomain: 'flutter-firebase-project-882a5.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-882a5.firebasestorage.app',
    measurementId: 'G-FS6Y3JTLBM',
  );
}
