import 'dart:convert';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:new_firebase/users.dart';

class FetchApi extends StatefulWidget {
  const FetchApi({super.key});

  @override
  State<FetchApi> createState() => _FetchApiState();
}

class _FetchApiState extends State<FetchApi> {
  List usersList = [];

  Future<List> fetchintAPI() async {
    http.Response response;
    response = await http.get(
      Uri.parse("https://jsonplaceholder.typicode.com/users"),
    );
    if (response.statusCode == 200) {
      var data = jsonDecode(response.body.toString());
      for (Map i in data) {
        usersList.add(Autogenerated.fromJson(i));
      }
      return usersList;
    } else {
      throw Exception("Failed to load data");
    }
  }

  Future<User> fetchUserById(String? id) async {
    http.Response response;
    response = await http.get(
      Uri.parse("https://jsonplaceholder.typicode.com/users/${id}"),
    );
    if (response.statusCode == 200) {
      var data = jsonDecode(response.body.toString());
      print('user data : ${data}');
      return data;
    } else {
      throw Exception("Failed to load data");
    }
  }

  @override
  void initState() {
    super.initState();
    fetchintAPI();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Users List"), backgroundColor: Colors.blue),
      body: Column(
        children: [
          Expanded(
            child: FutureBuilder(
              future: fetchintAPI(),
              builder: (context, snapshot) {
                if (!snapshot.hasData) {
                  return Text('Loading');
                } else {
                  return ListView.builder(
                    itemBuilder: (context, index) {
                      return GestureDetector(
                        onTap: () async {
                          User u = await fetchUserById(
                            '${usersList[index].id}',
                          );
                        },
                        child: Card(
                          elevation: 10,
                          margin: EdgeInsets.all(10),
                          child: ListTile(
                            leading: Text(
                              '${usersList[index].id}',
                              style: TextStyle(fontSize: 25),
                            ),
                            title: Text(
                              '${usersList[index].name}',
                              style: TextStyle(fontSize: 20),
                            ),
                            subtitle: Text(
                              '${usersList[index].username}',
                              style: TextStyle(fontSize: 20),
                            ),
                          ),
                        ),
                      );
                    },
                    itemCount: usersList.length,
                  );
                }
              },
            ),
          ),
        ],
      ),
    );
  }
}
