// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS1iI1rlWFqYv1E5j8M9C4RRM_YMt73mE',
    appId: '1:951979085726:web:66cd055900ae5b96bd108f',
    messagingSenderId: '951979085726',
    projectId: 'new-flutter-firebase-pro-43224',
    authDomain: 'new-flutter-firebase-pro-43224.firebaseapp.com',
    storageBucket: 'new-flutter-firebase-pro-43224.firebasestorage.app',
    measurementId: 'G-WH4K6DRKJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcRaUF--JyluPcC-goAV-kIV71DLishHg',
    appId: '1:951979085726:android:c3b8c870a6ad61febd108f',
    messagingSenderId: '951979085726',
    projectId: 'new-flutter-firebase-pro-43224',
    storageBucket: 'new-flutter-firebase-pro-43224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBOdzEWOq61rh_kKBUe6EJ1ELRxSzjUN4',
    appId: '1:951979085726:ios:1fdf2148766ae720bd108f',
    messagingSenderId: '951979085726',
    projectId: 'new-flutter-firebase-pro-43224',
    storageBucket: 'new-flutter-firebase-pro-43224.firebasestorage.app',
    iosBundleId: 'com.example.newFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBOdzEWOq61rh_kKBUe6EJ1ELRxSzjUN4',
    appId: '1:951979085726:ios:1fdf2148766ae720bd108f',
    messagingSenderId: '951979085726',
    projectId: 'new-flutter-firebase-pro-43224',
    storageBucket: 'new-flutter-firebase-pro-43224.firebasestorage.app',
    iosBundleId: 'com.example.newFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS1iI1rlWFqYv1E5j8M9C4RRM_YMt73mE',
    appId: '1:951979085726:web:8ad874e2afdc6ca4bd108f',
    messagingSenderId: '951979085726',
    projectId: 'new-flutter-firebase-pro-43224',
    authDomain: 'new-flutter-firebase-pro-43224.firebaseapp.com',
    storageBucket: 'new-flutter-firebase-pro-43224.firebasestorage.app',
    measurementId: 'G-0BB8HRJYW5',
  );
}
