// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1LZbZq1MP4Oh8lpfaGLfkWzf50mlqOeo',
    appId: '1:424826272393:web:c15c06a5211b6c6c05a458',
    messagingSenderId: '424826272393',
    projectId: 'module-6-d6ba0',
    authDomain: 'module-6-d6ba0.firebaseapp.com',
    storageBucket: 'module-6-d6ba0.firebasestorage.app',
    measurementId: 'G-P83T0DMKVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAthrbb_yd1OXEtDcNkAZRNTyy51eVObY8',
    appId: '1:424826272393:android:ec9d221d9fc80aaf05a458',
    messagingSenderId: '424826272393',
    projectId: 'module-6-d6ba0',
    storageBucket: 'module-6-d6ba0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPO_9-JvT2SeGejaHf8Ip8HsBQVXNj5no',
    appId: '1:424826272393:ios:c2ec0d22776dfd0405a458',
    messagingSenderId: '424826272393',
    projectId: 'module-6-d6ba0',
    storageBucket: 'module-6-d6ba0.firebasestorage.app',
    iosBundleId: 'com.example.module6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPO_9-JvT2SeGejaHf8Ip8HsBQVXNj5no',
    appId: '1:424826272393:ios:c2ec0d22776dfd0405a458',
    messagingSenderId: '424826272393',
    projectId: 'module-6-d6ba0',
    storageBucket: 'module-6-d6ba0.firebasestorage.app',
    iosBundleId: 'com.example.module6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1LZbZq1MP4Oh8lpfaGLfkWzf50mlqOeo',
    appId: '1:424826272393:web:2846e961d06a4ce305a458',
    messagingSenderId: '424826272393',
    projectId: 'module-6-d6ba0',
    authDomain: 'module-6-d6ba0.firebaseapp.com',
    storageBucket: 'module-6-d6ba0.firebasestorage.app',
    measurementId: 'G-YCLFJBJQCS',
  );
}
