// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYPYJ33PEz048Ncz0DJ3CxbZ6XQGRkOxs',
    appId: '1:568551951764:web:37846d7961adb3d4891381',
    messagingSenderId: '568551951764',
    projectId: 'module-10-cdd85',
    authDomain: 'module-10-cdd85.firebaseapp.com',
    storageBucket: 'module-10-cdd85.firebasestorage.app',
    measurementId: 'G-48HFEKZLKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1EcI38fLEuK8XO8OdvKRxlJ8sme3hUZs',
    appId: '1:568551951764:android:f57ada7642d56650891381',
    messagingSenderId: '568551951764',
    projectId: 'module-10-cdd85',
    storageBucket: 'module-10-cdd85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1wxhPBwTGGl736ywqQp9oUPJ9hOEjAnY',
    appId: '1:568551951764:ios:1a489bdc003efc90891381',
    messagingSenderId: '568551951764',
    projectId: 'module-10-cdd85',
    storageBucket: 'module-10-cdd85.firebasestorage.app',
    iosClientId: '568551951764-jl9u761s3ch0podnvnhtea3lqskjf977.apps.googleusercontent.com',
    iosBundleId: 'com.example.module10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1wxhPBwTGGl736ywqQp9oUPJ9hOEjAnY',
    appId: '1:568551951764:ios:1a489bdc003efc90891381',
    messagingSenderId: '568551951764',
    projectId: 'module-10-cdd85',
    storageBucket: 'module-10-cdd85.firebasestorage.app',
    iosClientId: '568551951764-jl9u761s3ch0podnvnhtea3lqskjf977.apps.googleusercontent.com',
    iosBundleId: 'com.example.module10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYPYJ33PEz048Ncz0DJ3CxbZ6XQGRkOxs',
    appId: '1:568551951764:web:7c96f4cbfbba059f891381',
    messagingSenderId: '568551951764',
    projectId: 'module-10-cdd85',
    authDomain: 'module-10-cdd85.firebaseapp.com',
    storageBucket: 'module-10-cdd85.firebasestorage.app',
    measurementId: 'G-G55DRYBB6M',
  );

}